version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: nfl_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nfl_data
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./api
    container_name: nfl_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: nfl_data

  frontend:
    build: ./frontend
    container_name: nfl_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  db_data:
